# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(db_column='visitor_id', primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('purpose_of_visit', models.CharField(max_length=100)),
                ('whom_to_visit', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_file', models.FileField(blank=True, null=True, upload_to='visitors_image/')),
                ('photo_path', models.CharField(blank=True, max_length=250, null=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('visit_end_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'Visitor',
            },
        ),
    ]
