# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('employee_assignment_id', models.AutoField(db_column='employee_assignment_id', primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.designation')),
                ('employee_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeAssignment',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCourse',
            fields=[
                ('employee_course_id', models.AutoField(db_column='employee_course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_place', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('course_results', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeCourse',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=50)),
                ('document_file', models.FileField(max_length=50, upload_to='employee_documents/')),
                ('document_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeDocument',
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('employee_experience_id', models.AutoField(db_column='employee_experience_id', primary_key=True, serialize=False)),
                ('previous_company_worked', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason_for_leaving', models.CharField(max_length=500)),
                ('experience_letter_provided', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeExperience',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFamilyDetail',
            fields=[
                ('family_detail_id', models.AutoField(db_column='family_detail_id', primary_key=True, serialize=False)),
                ('employee_relation', models.CharField(max_length=50)),
                ('relation_title', models.CharField(max_length=50)),
                ('relation_first_name', models.CharField(max_length=100)),
                ('relation_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_last_name', models.CharField(max_length=100)),
                ('relation_dob', models.DateField()),
                ('relation_marital_status', models.CharField(max_length=50)),
                ('relation_employed', models.CharField(max_length=50)),
                ('relation_occupation', models.CharField(max_length=100)),
                ('relation_dependent', models.CharField(max_length=1)),
                ('relation_pf_nominee', models.CharField(max_length=1)),
                ('relation_pf_share', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('relation_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.gender')),
            ],
            options={
                'db_table': 'EmployeeFamilyDetail',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLanguage',
            fields=[
                ('employee_language_id', models.AutoField(db_column='employee_language_id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeLanguage',
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('employee_qualification_id', models.AutoField(db_column='employee_qualification_id', primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=50)),
                ('highest_qualification', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('university', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EmployeeQualification',
            },
        ),
    ]
