# Generated by Django 5.2.7 on 2025-12-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('storage_backend', models.CharField(choices=[('LOCAL', 'Local Storage'), ('S3', 'Amazon S3')], default='LOCAL', max_length=20)),
                ('path_or_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DocumentFile',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('group_type', models.CharField(choices=[('ORG', 'Organization'), ('BRANCH', 'Branch / Campus'), ('STUDENT', 'Student'), ('EMPLOYEE', 'Employee / Staff'), ('LIBRARY', 'Library'), ('CIRCULAR', 'Circular / Notice'), ('SUBJECT_DOCUMENT', 'Subject Document'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DocumentGroup',
            },
        ),
    ]
