# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ACADEMIC_DOCUMENTS', '0001_initial'),
        ('Acadix', '0001_initial'),
        ('Library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.course'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='library_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Library.librarybranch'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.section'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.coursedepartmentsubject'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ACADEMIC_DOCUMENTS.documentgroup'),
        ),
        migrations.AddIndex(
            model_name='documentgroup',
            index=models.Index(fields=['organization', 'branch', 'group_type', 'code'], name='DocumentGro_organiz_908d84_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['group', 'is_current', 'is_active'], name='DocumentFil_group_i_f96203_idx'),
        ),
    ]
