# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('topic_id', models.AutoField(db_column='topicId', primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.coursedepartmentsubject')),
            ],
            options={
                'db_table': 'SubjectTopic',
            },
        ),
        migrations.CreateModel(
            name='LecturePlan',
            fields=[
                ('lecture_plan_id', models.AutoField(db_column='lecture_plan_id', primary_key=True, serialize=False)),
                ('lecture_no', models.IntegerField()),
                ('module_no', models.CharField(blank=True, max_length=100, null=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('taught_date', models.DateField(blank=True, null=True)),
                ('percentage_completed', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.coursedepartmentsubject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIME_TABLE.subjecttopic')),
            ],
            options={
                'db_table': 'LecturePlan',
            },
        ),
    ]
