# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_type',
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='REPORT_CARD.examtype')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='Acadix.studentcourse')),
            ],
            options={
                'db_table': 'student_exam_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoScholasticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_scholastic_results', to='REPORT_CARD.studentexamresult')),
            ],
            options={
                'db_table': 'co_scholastic_result',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_attendance', models.IntegerField(blank=True, null=True)),
                ('possible_attendance', models.IntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='REPORT_CARD.studentexamresult')),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_pdf', models.FileField(upload_to='report_cards/')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='Acadix.studentcourse')),
            ],
            options={
                'db_table': 'student_report_card',
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('periodic_assessment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notebook_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subject_enrichment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('theory_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_pass', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='REPORT_CARD.studentexamresult')),
            ],
            options={
                'db_table': 'subject_result',
            },
        ),
        migrations.CreateModel(
            name='TeacherRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_remarks', models.TextField(blank=True, null=True)),
                ('principal_remarks', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('competitions', models.TextField(blank=True, null=True)),
                ('co_curricular_participation', models.TextField(blank=True, null=True)),
                ('holiday_homework', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_remarks', to='REPORT_CARD.studentexamresult')),
            ],
            options={
                'db_table': 'teacher_remarks',
            },
        ),
    ]
