# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievancePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_type', models.CharField(max_length=255)),
                ('priority_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'GrievancePriority',
            },
        ),
        migrations.CreateModel(
            name='GrievanceSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_type', models.CharField(max_length=255)),
                ('severity_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'GrievanceSeverity',
            },
        ),
        migrations.CreateModel(
            name='GrievanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_type_code', models.CharField(max_length=255)),
                ('grievance_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'GrievanceType',
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_number', models.BigIntegerField()),
                ('details', models.CharField(max_length=5000)),
                ('status', models.BooleanField(default=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=5000, null=True)),
                ('action_taken_by', models.PositiveIntegerField(blank=True, null=True)),
                ('action_taken_date_time', models.DateTimeField(blank=True, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='grievance_documents/')),
                ('doc_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('student_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentcourse')),
                ('grievance_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRIEVANCE.grievancepriority')),
                ('grievance_severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRIEVANCE.grievanceseverity')),
                ('grievance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRIEVANCE.grievancetype')),
            ],
            options={
                'db_table': 'Grievance',
            },
        ),
    ]
