# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('mou_id', models.AutoField(primary_key=True, serialize=False)),
                ('mou_details', models.TextField()),
                ('document_file', models.FileField(upload_to='mou_documents/')),
                ('mou_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'MOU',
            },
        ),
    ]
