# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryMaster',
            fields=[
                ('expense_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(max_length=200)),
                ('enabled', models.CharField(default='Y', max_length=1)),
                ('category_type', models.CharField(blank=True, max_length=1, null=True)),
                ('category_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EXPENSE_CATEGORY_MASTER',
            },
        ),
        migrations.CreateModel(
            name='ExpenseHeader',
            fields=[
                ('expense_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expense_no', models.BigIntegerField()),
                ('party_reference', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'EXPENSE_HEADER',
            },
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('expense_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.expensecategorymaster')),
                ('expense_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.expenseheader')),
            ],
            options={
                'db_table': 'EXPENSE_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_no', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_reference', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ExpenseHeaderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.expenseheader')),
            ],
            options={
                'db_table': 'EXPENSE_PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='ExpensePaymentDetail',
            fields=[
                ('payment_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('applied_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ExpensePaymentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.expensepayment')),
                ('bankId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.bank')),
                ('bank_accountId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.bankaccountdetail')),
            ],
            options={
                'db_table': 'EXPENSE_PAYMENT_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_no', models.IntegerField()),
                ('income_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_no', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acadix.bankaccountdetail')),
                ('bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acadix.bank')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
            options={
                'db_table': 'OtherIncome',
            },
        ),
        migrations.CreateModel(
            name='OtherIncomeDetail',
            fields=[
                ('income_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.expensecategorymaster')),
                ('income_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.otherincome')),
            ],
            options={
                'db_table': 'OtherIncomeDetail',
            },
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=200)),
                ('customer_supplier', models.CharField(max_length=50)),
                ('enabled', models.CharField(default='Y', max_length=1)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('email_id', models.EmailField(blank=True, max_length=100, null=True)),
                ('party_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acadix.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acadix.country')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Acadix.state')),
            ],
            options={
                'db_table': 'PARTY_MASTER',
            },
        ),
        migrations.AddField(
            model_name='otherincome',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.partymaster'),
        ),
        migrations.AddField(
            model_name='expenseheader',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPENSE.partymaster'),
        ),
    ]
