# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='Acadix.department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='Acadix.employeemaster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MentorStudentCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_date', models.DateField()),
                ('communicated_with', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('GUARDIAN', 'Guardian'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('OTHER', 'Other')], max_length=20)),
                ('communicated_via', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('IN_PERSON', 'In Person'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('VIDEO_CALL', 'Video Call'), ('LETTER', 'Letter'), ('OTHER', 'Other')], max_length=20)),
                ('communication_details', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_communications', to='Acadix.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='MENTOR.mentor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_communications', to='Acadix.studentregistration')),
            ],
            options={
                'ordering': ['-communication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMentor',
            fields=[
                ('Assigned_id', models.AutoField(db_column='Assigned_id', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.employeemaster')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.section')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentcourse')),
            ],
            options={
                'db_table': 'StudentMentor',
            },
        ),
        migrations.CreateModel(
            name='StudentCommunication',
            fields=[
                ('communication_id', models.AutoField(db_column='communication_id', primary_key=True, serialize=False)),
                ('communicated_with', models.CharField(max_length=255)),
                ('communicated_via', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.section')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
                ('assigned_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MENTOR.studentmentor')),
            ],
            options={
                'db_table': 'StudentCommunication',
            },
        ),
        migrations.CreateModel(
            name='StudentMentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='Acadix.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='MENTOR.mentor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='Acadix.studentregistration')),
            ],
            options={
                'unique_together': {('academic_year', 'mentor', 'student', 'is_primary')},
            },
        ),
    ]
