# Generated by Django 5.2.7 on 2025-12-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TrainingPlacement',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('company_name', models.CharField(max_length=250)),
        #         ('module', models.CharField(max_length=250)),
        #         ('duration', models.CharField(max_length=250)),
        #         ('from_date', models.DateField()),
        #         ('to_date', models.DateField()),
        #         ('participants', models.IntegerField(blank=True, null=True)),
        #         ('hr_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('is_active', models.BooleanField(default=True)),
        #         ('created_by', models.PositiveIntegerField()),
        #         ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear')),
        #         ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch')),
        #         ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
        #         ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.course')),
        #         ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department')),
        #         ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
        #         ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester')),
        #     ],
        #     options={
        #         'db_table': 'TrainingPlacement',
        #     },
        # ),
    ]
